### ISSUE TITLE
PowerView fails when attempting to login with a computer account

### ISSUE THREAD

**Issue by JeffTheDev00** [aniqfakhrul/powerview.py#73]
`Problem` : Powerview fails when attempting to connect with a computer account

`Output` : 

```
powerview 'test-domain/client01$@10.10.10.10' --use-ldap --dc-ip 10.10.10.10 -H <ntlm hash here>                      
[2023-12-15 01:48:59] LDAP Signing NOT Enforced!
Traceback (most recent call last):
  File "/usr/local/bin/powerview", line 33, in <module>
    sys.exit(load_entry_point('powerview==0.5.1', 'console_scripts', 'powerview')())
  File "/usr/local/lib/python3.10/dist-packages/powerview-0.5.1-py3.10.egg/powerview/__init__.py", line 38, in main
    powerview = PowerView(conn, args)
  File "/usr/local/lib/python3.10/dist-packages/powerview-0.5.1-py3.10.egg/powerview/powerview.py", line 77, in __init__
    self.is_admincount = bool(self.get_domainuser(identity=self.username, properties=["adminCount"])[0]["attributes"]["adminCount"])
IndexError: list index out of range
```

`Explanation` : It seems that that the `adminCount` attribute cannot be found in ldap when connecting with a computer account. Likely because computer accounts do not have this attribute set which causes the script to fail as its not able to find the value and can't proceed without it.

`Temporary Resolution` :
It seems that removing the following lines fixes the issue for now. 
![image](https://github.com/aniqfakhrul/powerview.py/assets/155991012/ee0f97b2-6cb5-4043-b55e-aa2a569efd9a)

**Comment by aniqfakhrul** [comment]
Thanks for pointing this out. This us because powerview checks current user admin status by querying adminCount attribute which is not the case for computer accounts. We'll fix this. Thanks again

**Comment by JeffTheDev00** [comment]
Happy to help!

**Comment by JeffTheDev00** [comment]
Btw, it seems like this code from last week's commit fixes it : 
```
 try:
            curUserDetails = self.get_domainuser(identity=self.username, properties=["adminCount","memberOf"])[0]

            userGroup = curUserDetails.get("attributes").get("memberOf")
            if isinstance(userGroup, str):
                groups.append(userGroup)
            elif isinstance(userGroup, list):
                groups = userGroup 

            for group in groups:
                if "CN=Domain Admins".casefold() in group.casefold():
                    self.is_domainadmin = True
                    break

            if self.is_domainadmin:
                logging.info(f"User {self.username} is a Domain Admin")
            else:
                self.is_admincount = bool(curUserDetails["attributes"]["adminCount"])
                if self.is_admincount:
                    logging.info(f"User {self.username} has adminCount attribute set to 1. Might be admin somewhere somehow :)")
        except:
            logging.debug("Failed to check user admin status")
```

**Comment by aniqfakhrul** [comment]
Have you tried if it works with computer account?

**Comment by JeffTheDev00** [comment]
Nope haven't tried it yet, will give it a shot in a bit!

**Comment by aniqfakhrul** [comment]
Thats good to know. I'll do some code cleaning to handle the errors.
